let PEOPLE = {
    "2manydjs": 2,
    "999999999": 1,
    "A-Trak": 1,
    "Adam Beyer": 1,
    "Alison Wonderland": 1,
    "Anti Up": 2,
    "Anyma": 1,
    "Aphex Twin": 1,
    "Armand van Helden": 1,
    "Artbat": 2,
    "Axwell": 1, "Steve Angello": 1, "Sebastian Ingrosso": 1,
    "BICEP": 2,
    "Barry Can't Swim": 1,
    "Black Coffee": 1,
    "Bob Moses": 2,
    "Boris Brejcha": 1,
    "Camelphat": 2,
    "Caribou": 1,
    "Carl Cox": 1,
    "Channel Tres": 1,
    "Charlotte de Witte": 1,
    "Chris Lake": 1,
    "Chris Liebing": 1,
    "Chromeo": 2,
    "Cirez D": 1,
    "Claptone": 1,
    "Cloonee": 1,
    "DJ Koze": 1,
    "DJ Seinfeld": 1,
    "DJ Snake": 1,
    "Dart Punk": 2,
    "Deadmau5": 1,
    "Deep Dish": 2,
    "Dillon Francis": 1,
    "Diplo": 1,
    "Disclosure": 2,
    "Dom Dolla": 1,
    "Duck Sauce": 2,
    "Duke Dumont": 1,
    "Eli & Fur": 1,
    "Enrico Sangiuliano": 1,
    "Eric Prydz": 1,
    "Everything Always": 2,
    "Fatboy Slim":1,
    "Fisher": 1,
    "Flight Facilities": 2,
    "Floating Points": 1,
    "Flume": 1,
    "Four Tet": 1,
    "Fred Again": 1,
    "Gessafelstein": 1,
    "Gordo": 1,
    "Gorgon City": 2,
    "Green Velvet": 1,
    "Gryffin": 1,
    "HI-LO": 1,
    "Hardwell": 1,
    "Hayden James": 1,
    "Honey Dijon": 1,
    "Hot Since 82": 1,
    "Idris Elba": 1,
    "James Hype": 1,
    "Jamie Jones": 1,
    "Jamie XX": 1,
    "Jan Blomqvist": 1,
    "Jauz": 1,
    "SIDEPIECE": 2,
    "John Digweed": 1,
    "Steve Aoki": 1,
    "Armin van Buuren": 1,
    "John Summit": 1,
    "Above & Beyond": 3,
    "San Holo": 1,
    "Martin Garrix": 1,
    "RL Grime": 1,
    "Justice": 2,
    "Kyle Watson": 1,
    "Marshmello": 1,
    "Kölsch": 1,
    "Lane 8": 1,
    "Lee Burridge": 1,
    "Louis the Child":  3,
    "MK": 1,
    "MRAK": 1,
    "Maceo Plex": 1,
    "Madeon": 1,
    "Mark Knight": 1,
    "Matador": 1,
    "Michael Bibi": 1,
    "Mochakk": 1,
    "Mura Masa": 1,
    "NGHTMRE": 1,
    "Nero": 3,
    "Nicole Moudaber": 1,
    "Nina Kraviz": 1,
    "Nora En Pure": 1,
    "Orbital": 2,
    "Oliver Heldens": 1,
    "Overmono": 2,
    "PAWSA": 1,
    "Patrick Mason": 1,
    "Peggy Gou": 1,
    "Pickle": 1,
    "Porter Robinson": 1,
    "Pryda": 1,
    "Purple Disco Machine": 1,
    "Reinier Zonneveld": 1,
    "Rezz": 1,
    "Richie Hawtin": 1,
    "Rüfüs Du Sol": 3,
    "SG Lewis": 1,
    "SOFI TUKKER": 2,
    "Sam Divine": 1,
    "Sasha & Digweed": 2,
    "Sasha": 1,
    "Skream": 1,
    "Skrillex": 1,
    "Solomun": 1,
    "Soulwax": "2 or more",
    "Stephan Bodzin": 1,
    "Sven Väth": 1,
    "Swedish House Mafia": 3,
    "TBA": 3,
    "TESTPILOT": 1,
    "Tale of Us": 2,
    "Tchami": 1,
    "The Blessed Madonna": 1,
    "The Chemical Brothers": 2,
    "The Martinez Brothers": 2,
    "Tinlicker": 2,
    "Underworld": 2,
    "Vintage Culture": 1,
    "Walker & Royce": 2,
    "Yotto": 1,
    "Zedd": 1,
};

let GROUPS = {
    "TBA": ["Skrillex", "Fred Again", "Four Tet"],
    "Anti Up": ["Chris Lake", "Chriz Lorenzo"],
    "Tale of Us": ["Anyma", "MRAK"],
    "Swedish House Mafia": ["Axwell", "Steve Angello", "Sebastian Ingrosso"],
    "Sasha & Digweed": ["Sasha", "John Digweed"],
    "Duck Sauce": ["Armand van Helden", "A-Trak"],
}

let ALIASES = [
    ["Eric Prydz", "Pryda", "Cirez D"],
    ["Deadmau5", "TESTPILOT"],
    ["Oliver Heldens",  "HI-LO"],
]
