let PEOPLE = {
    "2manydjs": 2,
    "999999999": 1,
    "A-Trak": 1,
    "ARTBAT": 2,
    "Above & Beyond": 3,
    "Adam Beyer": 1,
    "Alison Wonderland": 1,
    "Animal Riot": 2,
    "Anti Up": 2,
    "Anyma": 1,
    "Aphex Twin": 1,
    "Armand van Helden": 1,
    "Armin van Buuren": 1,
    "Axwell": 1,
    "BICEP": 2,
    "BLOND:ISH": 1,
    "Barry Can't Swim": 1,
    "Biscits": 1,
    "Black Coffee": 1,
    "Bob Moses": 2,
    "Bonobo": 1,
    "Boris Brejcha": 1,
    "CamelPhat": 2,
    "Cannons": 3,
    "Caribou": 1,
    "Carl Cox": 1,
    "Channel Tres": 1,
    "Charlotte de Witte": 1,
    "Chloé Robinson": 1,
    "Chris Avantgarde": 1,
    "Chris Lake": 1,
    "Chris Liebing": 1,
    "Chromeo": 2,
    "Cirez D": 1,
    "Claptone": 1,
    "Claude VonStroke": 1,
    "Cloonee": 1,
    "DESIREE": 1,
    "DJ Koze": 1,
    "DJ Seinfeld": 1,
    "DJ Snake": 1,
    "DRAMA": 1,
    "Daft Punk": 2,
    "Deadmau5": 1,
    "Deep Dish": 2,
    "Deeper Purpose": 1,
    "Dillon Francis": 1,
    "Diplo": 1,
    "Disclosure": 2,
    "Disfreq": 2,
    "Dom Dolla": 1,
    "Duck Sauce": 2,
    "Duke Dumont": 1,
    "Dusky": 2,
    "Elder Island": 3,
    "Eli & Fur": 2,
    "Enrico Sangiuliano": 1,
    "Eric Prydz": 1,
    "Erol Alkan": 1,
    "Everything Always": 2,
    "Fatboy Slim": 1,
    "Fisher": 1,
    "Flight Facilities": 2,
    "Floating Points": 1,
    "Flume": 1,
    "Four Tet": 1,
    "Franky Wah": 1,
    "Fred again..": 1,
    "Gessafelstein": 1,
    "Godford": 1,
    "Gordo": 1,
    "Gorgon City": 2,
    "Green Velvet": 1,
    "Gryffin": 1,
    "HI-LO": 1,
    "Hardwell": 1,
    "Hayden James": 1,
    "Honey Dijon": 1,
    "Hot Since 82": 1,
    "I Hate Models": 1,
    "Idris Elba": 1,
    "James Hype": 1,
    "Jamie Jones": 1,
    "Jamie xx": 1,
    "Jan Blomqvist": 1,
    "Jauz": 1,
    "Jerro": 1,
    "John Digweed": 1,
    "John Summit": 1,
    "Joseph Capriati": 1,
    "Justice": 2,
    "Klangkuenstler": 1,
    "Kyle Watson": 1,
    "Kölsch": 1,
    "L'Impératrice": 1,
    "Lane 8": 1,
    "Lee Burridge": 1,
    "Lewis OfMan": 1,
    "Louis the Child":  2,
    "Luke Alessi": 1,
    "MK": 1,
    "MRAK": 1,
    "Maceo Plex": 1,
    "Madeon": 1,
    "Mark Knight": 1,
    "Marshmello": 1,
    "Martin Garrix": 1,
    "Mason Collective": 2,
    "Matador": 1,
    "Mathame": 1,
    "Maya Jane Coles": 1,
    "Michael Bibi": 1,
    "Miss Monique": 1,
    "Mochakk": 1,
    "Moderat": 2,
    "Ms. Mada": 1,
    "Mura Masa": 1,
    "NGHTMRE": 1,
    "Narciss": 1,
    "Nero": 3,
    "Nicole Moudaber": 1,
    "Nina Kraviz": 1,
    "Nora En Pure": 1,
    "ODESZA": 2,
    "Oliver Heldens": 1,
    "Orbital": 2,
    "Overmono": 2,
    "PAWSA": 1,
    "Patrick Mason": 1,
    "Patrick Topping": 1,
    "Peggy Gou": 1,
    "Pickle": 1,
    "Porter Robinson": 1,
    "Pryda": 1,
    "Purple Disco Machine": 1,
    "RL Grime": 1,
    "Reinier Zonneveld": 1,
    "Rezz": 1,
    "Richie Hawtin": 1,
    "Ricky": 1,
    "Romy": 1,
    "Rossi.": 1,
    "Rüfüs Du Sol": 3,
    "SG Lewis": 1,
    "SIDEPIECE": 2,
    "SOFI TUKKER": 2,
    "Sam Divine": 1,
    "San Holo": 1,
    "Sasha & Digweed": 2,
    "Sasha": 1,
    "Sebastian Ingrosso": 1,
    "Silvie Loto": 1,
    "Skream": 1,
    "Skrillex": 1,
    "Solardo": 2,
    "Solomun": 1,
    "Sonny Fodera": 1,
    "Soulwax": "2 or more",
    "Stephan Bodzin": 1,
    "Stephan Jolk": 1,
    "Steve Angello": 1,
    "Steve Aoki": 1,
    "Sven Väth": 1,
    "Swedish House Mafia": 3,
    "TBA": 3,
    "TESTPILOT": 1,
    "TOKiMONSTA": 1,
    "Tale of Us": 2,
    "Tchami": 1,
    "The Avalanches": 2,
    "The Blessed Madonna": 1,
    "The Chemical Brothers": 2,
    "The Martinez Brothers": 2,
    "Tibasko": 2,
    "Tini Gessler": 1,
    "Tinlicker": 2,
    "Torren Foot": 1,
    "Underworld": 2,
    "VTSS": 1,
    "Vintage Culture": 1,
    "Walker & Royce": 2,
    "Wax Motif": 1,
    "Yotto": 1,
    "Zach2Mundo": 1,
    "Zedd": 1,
};

let GROUPS = {
    "Animal Riot": ["Zach2Mundo", "Ricky"],
    "TBA": ["Skrillex", "Fred again..", "Four Tet"],
    "Anti Up": ["Chris Lake", "Chriz Lorenzo"],
    "Tale of Us": ["Anyma", "MRAK"],
    "Swedish House Mafia": ["Axwell", "Steve Angello", "Sebastian Ingrosso"],
    "Sasha & Digweed": ["Sasha", "John Digweed"],
    "Duck Sauce": ["Armand van Helden", "A-Trak"],
}

let ALIASES = [
    ["Eric Prydz", "Pryda", "Cirez D"],
    ["Deadmau5", "TESTPILOT"],
    ["Oliver Heldens",  "HI-LO"],
]
